authen/urls.py
from django.urls import path


from authen.views import *


app_name = 'authen'
urlpatterns = [
    path('signout', logout_view, name='signout'),
    path('signup', signup, name='signup'),
]

dailyplan/urls.py
from django.urls import path

from dailyplan.views import *

app_name = 'plan'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('tasks', TaskListView.as_view(), name='tasks'),
    path('task/<int:pk>', TaskDetailView.as_view(), name='task'),
    path('task/create', TaskCreateView.as_view(), name='create'),
    path('task/update/<int:pk>', TaskUpdateView.as_view(), name='update'),
    path('task/delete/<int:pk>', TaskDeleteView.as_view(), name='delete'),
    path('week', WeekPlanView.as_view(), name='week'),
    path('day/<int:pk>', MyDayDetailView.as_view(), name='day'),
]

selfcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dailyplan.urls')),
    path('authen/', include('authen.urls')),
]

urlpatterns += staticfiles_urlpatterns()

authen/models.py
from django.db import models

# Create your models here.

dailyplan/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings

from django.urls import reverse

from dailyplan.scryps import time_convert


def positive_valid(value):
    if value <= 0:
        raise ValidationError('Time has to be greater then 0')


def time_valid(value):
    try:
        time_convert(value)
    except Exception as e:
        raise ValidationError('Some trouble has happened. Please, input another value')


class MyDay(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    day_date = models.DateField()

    def __str__(self):
        return self.day_date.__str__()


class Task(models.Model):
    title = models.CharField(max_length=128)
    status = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    day = models.ForeignKey(MyDay, on_delete=models.CASCADE, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('plan:day', kwargs={'pk': self.day.id})

    def __str__(self):
        return f'{self.title}: {self.status}'

dailyplan/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    model = Task
    fields = '__all__'

authen/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    logout(request)
    return render(request, 'registration/signout.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('plan:home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

dailyplan/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View, generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from datetime import date, timedelta

from .forms import TaskForm
from .models import *
# Create your views here.


class OwnerClass:
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


class HomeView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'dailyplan/home.html')


class TaskListView(OwnerClass, LoginRequiredMixin, generic.ListView):
    model = Task


class TaskDetailView(OwnerClass, LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Task
    fields = ['title']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return redirect(reverse_lazy('plan:tasks'))


class TaskUpdateView(OwnerClass, LoginRequiredMixin, generic.edit.UpdateView):
    model = Task
    fields = ['title', 'status']


class TaskDeleteView(OwnerClass, LoginRequiredMixin, generic.edit.DeleteView):
    model = Task

    def get_success_url(self):
        return self.request.session['theday']


class WeekPlanView(LoginRequiredMixin, View):
    @staticmethod
    def get_or_create_week(request):
        today = date.today()
        first_day_of_week = today - timedelta(days=today.weekday())
        whole_week = [first_day_of_week + timedelta(days=d) for d in range(7)]
        days = []
        tasks = []

        for day in whole_week:
            if not MyDay.objects.filter(day_date=str(day), owner=request.user):
                MyDay(day_date=str(day), owner=request.user).save()

            days.append(MyDay.objects.get(day_date=str(day), owner=request.user))

        # create dict with days and relative plans
        for day in days:
            day_tasks = Task.objects.filter(owner=request.user, day=day.id)
            tasks.append(day_tasks)

        weekday_names = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        return zip(days, tasks, weekday_names)

    def get(self, request):
        ctx = {'week': self.get_or_create_week(request)}
        return render(request, 'dailyplan/week.html', context=ctx)


class MyDayDetailView(OwnerClass, LoginRequiredMixin, View):
    template_name = 'dailyplan/day_detail.html'

    @staticmethod
    def get_ctx_obj(pk, user):
        try:
            obj = MyDay.objects.get(pk=pk, owner=user)
        except Exception as e:
            obj = None
        return obj

    def get(self, request, pk):
        task_titles = [task.title for task in Task.objects.filter(owner=request.user)]
        task_titles = set(task_titles)

        request.session['theday'] = request.path

        obj = self.get_ctx_obj(pk, request.user)

        this_day_tasks = Task.objects.filter(owner=request.user, day=obj.id)

        ctx = {'day': obj, 'task_titles': task_titles, 'next': request.path, 'tasks': this_day_tasks}

        return render(request, self.template_name, context=ctx)

    def post(self, request, pk):
        new_task_title = request.POST['task']

        request.session['theday'] = request.path

        if new_task_title:
            this_day = self.get_ctx_obj(pk, request.user)
            new_task, status = Task.objects.get_or_create(title=new_task_title, owner=request.user, day=this_day)

        return self.get(request, pk)

dailyplan/templates/dailyplan/day_detail.html
{% extends 'main_template.html' %}
{% load static %}

{% block title %} Day {% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'dailyplan/confirm_delete.css' %}">
{% endblock %}

{% block body %}
{% if day %}
    <p style=" margin-top: 5%;">{{ day.day_date }}</p>

    <form method="post">
        {% csrf_token %}
        <input style="width: 155px" type="text" name="task" list="tasktitles">
            <datalist id="tasktitles">
                <option value="TASK1">
                {% for task in task_titles %}
                    <option value="{{ task }}">
                {% endfor %}
            </datalist>
        <input type="submit" style="border-radius: 15px;" value="Add Task">
    </form>


    {% if tasks %}
        {% for task in tasks %}
            <p>
                <h1>{{ task.title }}</h1>
                <label>
                    {% if task.status %}
                        <samp style="color: green;font-size: 13px">done</samp>
                    {% else %}
                        <samp style="color: red;"> in progress</samp>
                    {% endif %}
                </label>
            </p>
            <a href="{% url 'plan:update' task.id %}"><button>Change</button></a>
            <a href="{% url 'plan:delete' task.id %}"><button>Delete</button></a>
            <br>
        {% endfor %}
    {% else %}
        <p>You haven't any plans this day</p>
    {% endif %}
{% else %}
    <p>There are no such day in db</p>
{% endif %}
{% endblock %}

dailyplan/templates/dailyplan/home.html
{% extends "main_template.html" %}

{% block title %}
    Home
{% endblock %}

{% block body %}
    <h1 style="font-size: 35px; font-family:  monospace;color: #ABABAB;margin-top: 8%">Welcome!</h1>
    <a style="color: cadetblue "> User: {{ user.username }}<br>
        ID: {{ user.id }}</a>
{% endblock %}

dailyplan/templates/dailyplan/task_confirm_delete.html
{% extends 'main_template.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'dailyplan/confirm_delete.css' %}">
{% endblock %}

{% block title %} Delete? {% endblock %}
{% block body %}
    <h1 style="margin-top: 5%">Task delete</h1>
    <p>Are you sure that you want to delete task: {{ task }}?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
    </form>
{% endblock %}

dailyplan/templates/dailyplan/task_detail.html
{% extends 'main_template.html' %}

{% load int_to_time %}

{% block title %} Task {{task.id}} {% endblock %}

{% block body %}
    <h2>{{ task.title }}</h2>
    <p>Status: {% if task.status %} done {% else %} in progress {% endif %}</p>
{% endblock %}

dailyplan/templates/dailyplan/task_form.html
{% extends 'main_template.html' %}
{% load static %}

{% block title %} Form {% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'dailyplan/task_form.css' %}">
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>{{ form.title.label_tag }}
            <input class="inpt" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}"
                   value="{{ form.title.value }}" type="{{ form.title.widget_type }}"/>
        </p>
        <p style="margin-left: 11%"> {{ form.status.label_tag }}
            {{ form.status }}</p>

        <input class="btn" type="submit" value="Save">
    </form>
{% endblock %}

dailyplan/templates/dailyplan/task_list.html
{% extends 'main_template.html' %}

{% block title %} Tasks {% endblock %}

{% block body %}
    <br>
    <button><a href="{% url 'plan:create' %}">Create Task</a></button>
    {% if task_list %}
        {% for task in task_list %}

            <h1><a href="{% url 'plan:task' task.id %}">{{ task.title }}</a></h1>
            {% if task.status %} done {% else %} in progress {% endif %}<br>
            <a href="{% url 'plan:update' task.id %}">update</a> |
            <a href="{% url 'plan:delete' task.id %}">delete</a><br>
        {% endfor %}
    {% else %}
        <h2>There are no tasks</h2>
    {% endif %}

{% endblock %}

dailyplan/templates/dailyplan/week.html
{% extends 'main_template.html' %}
{% load static %}

{% block title %} Form {% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'dailyplan/style_week.css' %}">
{% endblock %}

{% block body %}
    {% for day, tasks, day_name in week %}
        <a href="{% url 'plan:day' day.id %}">
            <div>
                <h2>{{ day_name }}</h2>
                <h3>{{ day.day_date }}</h3>
                <hr>
                {% for task in tasks %}
                    <p>{{ task.title }}</p>
                {% endfor %}
            </div>
        </a>
    {% endfor %}
{% endblock %}

dailyplan/templates/main_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dailyplan/dp_main.css' %}">
    {% block head %} {% endblock %}
</head>
<body>
{% block nav %}
<nav>
    <a href="{% url 'plan:home' %}">Home</a>
    <a href="{% url 'plan:week' %}">Week</a>
    <a href="{% url 'login' %}">Log in</a>
    <a href="{% url 'authen:signout' %}">Log out</a>
    <a href="{% url 'authen:signup' %}">Sign up</a>
</nav>
{% endblock %}
{% block body %}
{% endblock %}
</body>
</html>